import { Vehicle } from "./types";

export const IMAGES = {
  logo: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_0.png",
  heroBg: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_1.png",
  xuv700: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_2.png",
  safari: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_3.png",
  ioniq6: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_4.png",
  ev6: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_5.png",
  vf8: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_6.png",
  xuv3xo: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_7.png",
  safariDark: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_8.png",
  be05: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_9.png",
  harrierev: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_10.png",
};

export const VEHICLES: Vehicle[] = [
  {
    id: "ioniq-6",
    name: "Ioniq 6 AWD",
    brand: "Hyundai",
    category: "Electric Vehicles",
    price: 47900,
    imageUrl: IMAGES.ioniq6,
    tagline: "Aerodynamic Serenity in Motion",
    description: "An exceptionally sleek, streamliner silhouette crafted to minimize drag and elevate performance. Featuring a state-of-the-art 800V high-speed architecture, the Ioniq 6 transforms your charging stops into brief transitions while cocooning you in an elegant, sustainably sourced interior.",
    specs: {
      acceleration: "5.1s",
      topSpeed: "115 mph",
      range: "361 mi",
      power: "320 HP",
      drivetrain: "Dual Motor AWD",
    },
    additionalSpecs: [
      { label: "Battery Capacity", value: "77.4 kWh", iconName: "battery" },
      { label: "Drag Coefficient", value: "0.21 Cd", iconName: "wind" },
      { label: "Fast Charging", value: "10% to 80% in 18 mins", iconName: "zap" },
      { label: "Cargo Space", value: "11.2 cu-ft", iconName: "archive" },
    ],
    colors: [
      { name: "Digital Teal", hex: "#1F4E5B", price: 0 },
      { name: "Gravity Gold Matt", hex: "#BEB2A7", price: 1000 },
      { name: "Abyss Black Pearl", hex: "#111111", price: 450 },
      { name: "Biophilic Blue", hex: "#0E1C36", price: 450 },
    ],
    trims: [
      { name: "SEL Performance", description: "Standard premium comfort with 20-inch alloy wheels, smart cabin features, and premium active safety.", price: 0 },
      { name: "Limited Luxury", description: "Adds wide sunroof, Blind-Spot View Monitor, Bose Premium audio, and Remote Smart Parking Assist.", price: 3500 },
      { name: "Bespoke Editorial", description: "Unrivaled design package featuring high-end sustainable leather cabin, dynamic pixel light accents, and sport styling.", price: 6200 },
    ],
    wheels: [
      { name: "18\" Aero Spoke", imageUrl: "", price: 0 },
      { name: "20\" Dynamic Cyber Alloy", imageUrl: "", price: 1200 },
    ],
    isLaunced: true,
  },
  {
    id: "ev-6",
    name: "EV6 GT-Line",
    brand: "Kia",
    category: "Electric Vehicles",
    price: 52600,
    imageUrl: IMAGES.ev6,
    tagline: "Bold Performance. Sustained Power.",
    description: "The EV6 GT-Line redefines the modern electric crossover with head-turning athleticism and razor-sharp steering. Equipped with ultra-fast charging capabilities and a high-fidelity visual footprint, it combines driver-centric ergonomics with sports car dynamics.",
    specs: {
      acceleration: "4.6s",
      topSpeed: "117 mph",
      range: "310 mi",
      power: "320 HP",
      drivetrain: "Dual Motor AWD",
    },
    additionalSpecs: [
      { label: "Torque", value: "446 lb-ft", iconName: "gauge" },
      { label: "Power Outlet", value: "V2L Utility 1.9kW", iconName: "zap" },
      { label: "Charging Speed", value: "350 kW DC max", iconName: "battery-charging" },
      { label: "Sound System", value: "Meridian Premium 14-spk", iconName: "music" },
    ],
    colors: [
      { name: "Runway Red", hex: "#9E0B0F", price: 0 },
      { name: "Yacht Blue", hex: "#102F4E", price: 650 },
      { name: "Steel Gray Matte", hex: "#5C6163", price: 1200 },
      { name: "Aurora Black Pearl", hex: "#161719", price: 450 },
    ],
    trims: [
      { name: "GT-Line", description: "Dynamic exterior with sport seats, multi-color ambient lighting, and Augmented Reality Head-Up Display.", price: 0 },
      { name: "GT Performance Extreme", description: "Adds 21-inch wheels, adaptive suspension, neon green brake calipers, and Dedicated GT Drive Mode.", price: 8900 },
    ],
    wheels: [
      { name: "19\" Sport Shadow", imageUrl: "", price: 0 },
      { name: "21\" Diamond-Cut Aero Black", imageUrl: "", price: 1800 },
    ],
    isLaunced: true,
  },
  {
    id: "harrier-ev",
    name: "Harrier.ev Concept",
    brand: "Tata",
    category: "Futuristic Concepts",
    price: 42000,
    imageUrl: IMAGES.harrierev,
    tagline: "Electric Intelligence Meets Timeless Form",
    description: "Launced on our Gen-2 Pure EV Architecture, the Harrier.ev marries rugged adventure capability with pristine luxury. Powered by a highly versatile intelligent AWD system with terrain active management, it features vehicle-to-load and vehicle-to-vehicle charging, making it a dependable sanctuary in any environment.",
    specs: {
      acceleration: "6.4s",
      topSpeed: "124 mph",
      range: "320 mi",
      power: "280 HP",
      drivetrain: "Dual Motor AWD",
    },
    additionalSpecs: [
      { label: "Architecture", value: "Gen-2 EV Platform", iconName: "cpu" },
      { label: "Solar Canopy Compatibility", value: "Included", iconName: "sun" },
      { label: "V2V Sharing", value: "Up to 5 kW output", iconName: "share-2" },
      { label: "Water Wading", value: "450 mm depth", iconName: "droplet" },
    ],
    colors: [
      { name: "Solar Green Metallic", hex: "#3A5F43", price: 0 },
      { name: "Empress Frost White", hex: "#E9ECE9", price: 500 },
      { name: "Nebula Charcoal Grey", hex: "#303432", price: 500 },
    ],
    trims: [
      { name: "Adventure.ev", description: "Intuitive infotainment screen, robust off-road body protection, eco-synthetic textiles.", price: 0 },
      { name: "Empress.ev Luxury", description: "Bespoke ambient light canopy, solar-charging micro panels, multi-zone climate lounge, biomorphic seating.", price: 4200 },
    ],
    wheels: [
      { name: "19\" Cyber Aero Green", imageUrl: "", price: 0 },
      { name: "20\" Solid-Block Matte-Black", imageUrl: "", price: 1400 },
    ],
    isLaunced: false,
    launchDate: "Winter 2026",
  },
  {
    id: "be-05",
    name: "BE.05 Born EV",
    brand: "Mahindra",
    category: "Futuristic Concepts",
    price: 75000,
    imageUrl: IMAGES.be05,
    tagline: "Sports Electric Vehicle (SEV) Reborn",
    description: "The BE.05 is an uncompromising, racing-born SUV concept designed to trigger your adrenaline. Sculpted with high-aerodynamic ducts and a multi-display fighter-cockpit interior, it runs on our advanced INGLO platform, delivering massive instantaneous torque and cutting-edge augmented navigation.",
    specs: {
      acceleration: "3.5s",
      topSpeed: "140 mph",
      range: "285 mi",
      power: "340 HP",
      drivetrain: "Rear-biased AWD",
    },
    additionalSpecs: [
      { label: "Platform", value: "INGLO Born EV", iconName: "layers" },
      { label: "Aerodynamic Intakes", value: "Dual front hood-scoops", iconName: "wind" },
      { label: "AI Copilot", value: "Level 3+ potential", iconName: "cpu" },
      { label: "Audio Experience", value: "Spatial Sonic Bubble", iconName: "volume-2" },
    ],
    colors: [
      { name: "Cyber Silver Matte", hex: "#A8ADB1", price: 0 },
      { name: "Stealth Iron Black", hex: "#232628", price: 900 },
      { name: "Electric Blue Burst", hex: "#0047AB", price: 900 },
    ],
    trims: [
      { name: "SEV Stealth Tech", description: "High-contrast digital glass canopy, carbon-fiber composites, active predictive handling.", price: 0 },
      { name: "SEV Circuit Master", description: "Fully customized racing cockpit, dual digital HUD, track performance logging, active aerodynamic stabilizers.", price: 9500 },
    ],
    wheels: [
      { name: "20\" Blade-Runner Concept Alloys", imageUrl: "", price: 0 },
      { name: "21\" Multi-Beam Futuristic Alloys", imageUrl: "", price: 2500 },
    ],
    isLaunced: false,
    launchDate: "Summer 2027",
  },
  {
    id: "safari-dark",
    name: "Safari Dark Edition",
    brand: "Tata",
    category: "Performance Lab",
    price: 38500,
    imageUrl: IMAGES.safariDark,
    tagline: "An Elegant Shadow of Power",
    description: "Cloaked in absolute mystery. The Safari Dark Edition features a stunning Oberon Black exterior with a deep piano-black front grille, pristine dark-grey trim elements, and signature dark-stonewashed premium leather seating. This premium 3-row cruiser commands silence while offering unmatched acoustic isolation.",
    specs: {
      acceleration: "8.7s",
      topSpeed: "118 mph",
      range: "N/A",
      power: "170 HP",
      drivetrain: "FWD / Terrain Active",
    },
    additionalSpecs: [
      { label: "Engine", value: "2.0L Kryotec Turbo", iconName: "cog" },
      { label: "Seating Layout", value: "6 or 7-Seater Luxury", iconName: "users" },
      { label: "Acoustics", value: "JBL 10-speaker Spatial", iconName: "music" },
      { label: "Air Purification", value: "Ozone Auto Shield", iconName: "shield" },
    ],
    colors: [
      { name: "Oberon Black", hex: "#121314", price: 0 },
      { name: "Cosmic Charcoal Matte", hex: "#2E3033", price: 1000 },
    ],
    trims: [
      { name: "Dark Adventure", description: "Black-themed body lining, dark alloys, fully digital dashboard, ventilating pilot captain seats.", price: 0 },
      { name: "Dark Accomplished Plus", description: "Adds dynamic gesture tailgate, memory seats, personalized welcoming visual signatures, dynamic ADAS Suite.", price: 3000 },
    ],
    wheels: [
      { name: "19\" Blackstone Alloy", imageUrl: "", price: 0 },
      { name: "20\" Dark Stealth Multi-Spoke", imageUrl: "", price: 1500 },
    ],
    isLaunced: true,
  },
  {
    id: "xuv700",
    name: "XUV700 Luxury",
    brand: "Mahindra",
    category: "Luxury SUVs",
    price: 34500,
    imageUrl: IMAGES.xuv700,
    tagline: "Uncompromised Safety. Intelligent Power.",
    description: "Engineered to deliver exceptional security and performance across all landscapes. The XUV700 stands out with a robust structural shell, dual 10.25-inch high-resolution cinematic display screens, ADAS safety features, and a high-efficiency performance powertrain that turns every mountain road into a tranquil breeze.",
    specs: {
      acceleration: "9.2s",
      topSpeed: "121 mph",
      range: "N/A",
      power: "200 HP",
      drivetrain: "Intelligent AWD",
    },
    additionalSpecs: [
      { label: "Engine", value: "2.0L mStallion Turbo", iconName: "cog" },
      { label: "Cabin Tech", value: "AdreNoX Connect System", iconName: "smartphone" },
      { label: "Sunroof", value: "Panoramic Skyroof", iconName: "sun" },
      { label: "ADAS Tech", value: "ADAS Level 2 certified", iconName: "shield" },
    ],
    colors: [
      { name: "Everest White Pearl", hex: "#F3F5F7", price: 0 },
      { name: "Midnight Black Blue", hex: "#0A131F", price: 0 },
      { name: "Dazzling Silver Metallic", hex: "#D6D9DC", price: 0 },
      { name: "Electric Blue", hex: "#11468F", price: 500 },
    ],
    trims: [
      { name: "AX7 Premium", description: "Comprehensive driver-assist, premium seating comfort, full digital AdreNoX setup.", price: 0 },
      { name: "AX7 Luxury Pack", description: "Adds 3D Immersive Audio by Sony (12-spk), Blind-view monitor, 360 camera, electronic smart door handles.", price: 2900 },
    ],
    wheels: [
      { name: "18\" Diamond Cut Alloys", imageUrl: "", price: 0 },
      { name: "19\" Custom Chrome Spoke", imageUrl: "", price: 1100 },
    ],
    isLaunced: true,
  },
  {
    id: "safari-silver",
    name: "Safari Accomplished Plus",
    brand: "Tata",
    category: "Luxury SUVs",
    price: 36200,
    imageUrl: IMAGES.safari,
    tagline: "An Icon of Modern Prestige",
    description: "Combining majestic presence with intricate digital craft. Designed with an assertive geometric stance, premium silver highlights, and a luxurious dual-tone dashboard, it elevates family cruiser travel. Pampering captain seating and personalized cabin settings provide immense decision-breathing-room on long commutes.",
    specs: {
      acceleration: "9.5s",
      topSpeed: "115 mph",
      range: "N/A",
      power: "170 HP",
      drivetrain: "FWD / Multi-Terrain",
    },
    additionalSpecs: [
      { label: "Engine", value: "2.0L Kryotec Diesel", iconName: "cog" },
      { label: "Acoustics", value: "JBL Premium 9-speaker", iconName: "music" },
      { label: "Headlights", value: "Sequential LED Bars", iconName: "eye" },
      { label: "Climate Control", value: "Dual Zone Auto Air", iconName: "wind" },
    ],
    colors: [
      { name: "Stellar Silver", hex: "#D0D3D4", price: 0 },
      { name: "Glacier White", hex: "#F7F9FA", price: 0 },
      { name: "Galactic Grey", hex: "#63666A", price: 450 },
    ],
    trims: [
      { name: "Adventure Plus", description: "Electronic stability, 19\" alloys, wireless smartphone charging, voice sunroof.", price: 0 },
      { name: "Accomplished Plus", description: "Panoramic sky canopy with mood lighting, 360-degree surround vision camera, luxury ventilation for first 2 rows.", price: 3400 },
    ],
    wheels: [
      { name: "19\" Sleek Sport Alloys", imageUrl: "", price: 0 },
      { name: "20\" Satin Finish Chrome", imageUrl: "", price: 1300 },
    ],
    isLaunced: true,
  },
  {
    id: "vf8",
    name: "VF8 Plus AWD",
    brand: "VinFast",
    category: "Electric Vehicles",
    price: 46000,
    imageUrl: IMAGES.vf8,
    tagline: "Dynamic Elegance. Pininfarina Design.",
    description: "Engineered in partnership with legendary Italian studio Pininfarina. The VF8 Plus boasts breathtaking proportions that blend high aerodynamic prowess with spacious interior comfort. Underpinned by smart connected services, it puts advanced voice intelligence and high-power performance at your disposal.",
    specs: {
      acceleration: "5.5s",
      topSpeed: "124 mph",
      range: "264 mi",
      power: "402 HP",
      drivetrain: "Dual Motor AWD",
    },
    additionalSpecs: [
      { label: "Torque", value: "457 lb-ft", iconName: "gauge" },
      { label: "Battery Pack", value: "87.7 kWh usable", iconName: "battery" },
      { label: "Warranty", value: "10 Years / 125k mi", iconName: "shield" },
      { label: "Infotainment", value: "15.6\" Touch Screen", iconName: "tv" },
    ],
    colors: [
      { name: "Eco Grey Matte", hex: "#7D8285", price: 0 },
      { name: "Crimson Red", hex: "#B81D24", price: 600 },
      { name: "VinFast Blue Pearl", hex: "#194F90", price: 600 },
      { name: "Silver Frost Pearl", hex: "#EAECED", price: 600 },
    ],
    trims: [
      { name: "Plus Edition", description: "Heated and ventilated seats, premium faux leather, smart active driving assist, panoramic skylight.", price: 0 },
      { name: "Pinnacle Premium", description: "Adds genuine organic Nappa leather cabin, premium spatial audio, smart cabin voice companion, and dynamic air suspension.", price: 4800 },
    ],
    wheels: [
      { name: "19\" Split-Spoke Alloys", imageUrl: "", price: 0 },
      { name: "20\" High-Contrast Platinum", imageUrl: "", price: 1200 },
    ],
    isLaunced: true,
  },
  {
    id: "xuv-3xo",
    name: "XUV 3XO AX7 L",
    brand: "Mahindra",
    category: "Performance Lab",
    price: 22800,
    imageUrl: IMAGES.xuv3xo,
    tagline: "Athletic Spirit. Urban Command.",
    description: "Compact yet aggressive, the XUV 3XO packs a staggering amount of technical sophistication and high-performance engineering. Featuring a refined mStallion TGDi turbo engine, segment-first level 2 ADAS capabilities, and a sweeping skyroof, it navigates congested cities and coastal lanes with unparalleled agility.",
    specs: {
      acceleration: "8.9s",
      topSpeed: "112 mph",
      range: "N/A",
      power: "130 HP",
      drivetrain: "FWD / Sport Tuned",
    },
    additionalSpecs: [
      { label: "Engine", value: "1.2L mStallion Turbo", iconName: "cog" },
      { label: "Safety ADAS", value: "Level 2 (10+ features)", iconName: "shield" },
      { label: "Sound Integration", value: "Harman Kardon Premium", iconName: "volume-2" },
      { label: "Fast Steering", value: "Electronic Sport Calibrated", iconName: "target" },
    ],
    colors: [
      { name: "Earthy Bronze Metallic", hex: "#8A6D53", price: 0 },
      { name: "Nebula Blue Accent", hex: "#1A365D", price: 400 },
      { name: "Stealth Black", hex: "#1C1C1C", price: 400 },
      { name: "Ivory White Premium", hex: "#FDFDFD", price: 0 },
    ],
    trims: [
      { name: "AX7 Comfort Tech", description: "Premium fabric dashboard wrap, dual screen 10.25\" infotainment, panoramic sunroof.", price: 0 },
      { name: "AX7 Luxury Edition", description: "Adds Electronic Parking Brake, 360-degree vision, premium Harman Kardon acoustics, blind spot monitor.", price: 1800 },
    ],
    wheels: [
      { name: "17\" Diamond-Cut Alloys", imageUrl: "", price: 0 },
      { name: "18\" Midnight-Black Alloys", imageUrl: "", price: 800 },
    ],
    isLaunced: true,
  }
];

export const TEST_LOCATIONS = [
  "AutoHaven Beverly Hills Gallery",
  "AutoHaven Silicon Valley Tech Lab",
  "AutoHaven Miami Beach Lounge",
  "AutoHaven Seattle Waterfront Studio"
];
