import { Vehicle } from "./types";

export const IMAGES = {
  logo: "/logo.png",
  heroBg: "https://storage.googleapis.com/test-session-bucket/ad03b17c-d8ba-41b6-81b8-86b932f8836b/input_file_1.png",
  xuv700: "/7xO images.avif",
  safari: "/Tata Safari.webp",
  sierraev: "/Tata-Sierra-EV-13-scaled.jpg",
  ev6: "/Kia EV8.jpg",
  vf8: "/Creta.webp",
  xuv3xo: "/mahindra-xuv-3xo-review-test-drive-11-1200x675.jpg",
  safariDark: "/Safari Dark Edition.avif",
  be05: "/Mahindra BE 6.webp",
  harrierev: "/Tata Harrier QWD.webp",
};

export const VEHICLES: Vehicle[] = [
  {
    id: "sierra-ev",
    name: "Sierra EV",
    brand: "Tata",
    category: "Electric Vehicles",
    price: 1879000,
    imageUrl: IMAGES.sierraev,
    tagline: "An Icon Reimagined for the Electric Age",
    description: "The Tata Sierra EV returns as a majestic, high-tech electric cruiser. Built with Tata's signature glasshouse silhouette, it offers immense cabin space, a 3-screen interactive display system, RWD and QWD drivetrain versatility, and a class-leading 622-litre boot layout.",
    specs: {
      acceleration: "6.8s",
      topSpeed: "110 mph",
      range: "375 mi",
      power: "200 HP",
      drivetrain: "Rear Wheel Drive (RWD)",
    },
    additionalSpecs: [
      { label: "Battery Pack Options", value: "63 kWh & 75 kWh", iconName: "battery" },
      { label: "DC Fast Charging", value: "20% to 80% in 26 mins", iconName: "zap" },
      { label: "Luggage Volume", value: "622 Litres", iconName: "archive" },
      { label: "Infotainment Panels", value: "Triple Screen Layout", iconName: "tv" },
      { label: "Safety Rating", value: "Level 2 ADAS active", iconName: "shield" },
    ],
    colors: [
      { name: "Empress Frost White", hex: "#E9ECE9", price: 0 },
      { name: "Solar Green Metallic", hex: "#3A5F43", price: 0 },
      { name: "Galactic Grey", hex: "#63666A", price: 45000 },
    ],
    trims: [
      { name: "Pure Tech", description: "Standard utility with 63 kWh battery pack, smart cluster panels, and active safety bags.", price: 0 },
      { name: "Empowered A AWD", description: "Dual-motor AWD layout, 75 kWh battery pack, augmented triple HUD system, and ADAS Level 2.", price: 720000 },
    ],
    wheels: [
      { name: "18\" Aero Alloys", imageUrl: "", price: 0 },
      { name: "19\" Sleek Sport Alloys", imageUrl: "", price: 80000 },
    ],
    isLaunched: true,
  },
  {
    id: "ev-6",
    name: "EV6 GT-Line",
    brand: "Kia",
    category: "Electric Vehicles",
    price: 6597000,
    imageUrl: IMAGES.ev6,
    tagline: "Bold Performance. Sustained Power.",
    description: "The EV6 GT-Line redefines the modern electric crossover with head-turning athleticism and razor-sharp steering. Equipped with ultra-fast charging capabilities and a high-fidelity visual footprint, it combines driver-centric ergonomics with sports car dynamics.",
    specs: {
      acceleration: "4.6s",
      topSpeed: "117 mph",
      range: "310 mi",
      power: "320 HP",
      drivetrain: "Dual Motor AWD",
    },
    additionalSpecs: [
      { label: "Torque", value: "446 lb-ft", iconName: "gauge" },
      { label: "Power Outlet", value: "V2L Utility 1.9kW", iconName: "zap" },
      { label: "Charging Speed", value: "350 kW DC max", iconName: "battery-charging" },
      { label: "Sound System", value: "Meridian Premium 14-spk", iconName: "music" },
    ],
    colors: [
      { name: "Runway Red", hex: "#9E0B0F", price: 0 },
      { name: "Yacht Blue", hex: "#102F4E", price: 65000 },
      { name: "Steel Gray Matte", hex: "#5C6163", price: 120000 },
      { name: "Aurora Black Pearl", hex: "#161719", price: 45000 },
    ],
    trims: [
      { name: "GT-Line", description: "Dynamic exterior with sport seats, multi-color ambient lighting, and Augmented Reality Head-Up Display.", price: 0 },
      { name: "GT Performance Extreme", description: "Adds 21-inch wheels, adaptive suspension, neon green brake calipers, and Dedicated GT Drive Mode.", price: 890000 },
    ],
    wheels: [
      { name: "19\" Sport Shadow", imageUrl: "", price: 0 },
      { name: "21\" Diamond-Cut Aero Black", imageUrl: "", price: 180000 },
    ],
    isLaunched: true,
  },
  {
    id: "harrier-ev",
    name: "Harrier EV QWD",
    brand: "Tata",
    category: "Electric Vehicles",
    price: 2649000,
    imageUrl: IMAGES.harrierev,
    tagline: "Electric Intelligence Meets All-Terrain Mastery",
    description: "Launched on the Tata Gen-2 Pure EV Architecture, the Harrier EV QWD merges tough adventure capabilities with exceptional cabin luxury. Offering high all-road torque and intelligent terrain active management, it features advanced vehicle-to-load utilities and full diagnostic safety controls.",
    specs: {
      acceleration: "6.4s",
      topSpeed: "124 mph",
      range: "310 mi",
      power: "280 HP",
      drivetrain: "Intelligent QWD AWD",
    },
    additionalSpecs: [
      { label: "Infotainment", value: "12.3\" Touchscreen System", iconName: "tv" },
      { label: "Sound Integration", value: "10-Speaker JBL Premium", iconName: "volume-2" },
      { label: "Driver Customization", value: "6-Way Power with Memory", iconName: "user" },
      { label: "Co-Driver Seat", value: "4-Way Powered Seat", iconName: "user-check" },
      { label: "Cabin Air Control", value: "Dual-Zone Climate Control", iconName: "wind" },
      { label: "Safety Assist", value: "360-Degree Camera active", iconName: "shield" },
    ],
    colors: [
      { name: "Solar Green Metallic", hex: "#3A5F43", price: 0 },
      { name: "Empress Frost White", hex: "#E9ECE9", price: 50000 },
      { name: "Nebula Charcoal Grey", hex: "#303432", price: 50000 },
    ],
    trims: [
      { name: "Adventure.ev", description: "Intuitive infotainment screen, robust off-road body protection, eco-synthetic textiles.", price: 0 },
      { name: "Fearless+ QWD 75", description: "Bespoke ambient light canopy, solar-charging micro panels, multi-zone climate lounge, biomorphic seating.", price: 420000 },
    ],
    wheels: [
      { name: "19\" Cyber Aero Green", imageUrl: "", price: 0 },
      { name: "20\" Solid-Block Matte-Black", imageUrl: "", price: 140000 },
    ],
    isLaunched: true,
  },
  {
    id: "be-6",
    name: "BE 6",
    brand: "Mahindra",
    category: "Electric Vehicles",
    price: 2400000,
    imageUrl: IMAGES.be05,
    tagline: "Futuristic. Electric. Exhilarating.",
    description: "The BE 6 coupe SUV marks the next phase in high-performance electric motoring. Sculpted with aggressive aerodynamic ducts, it runs on our advanced INGLO platform, delivering massive instantaneous torque and cutting-edge Level 2 ADAS controls.",
    specs: {
      acceleration: "6.7s",
      topSpeed: "124 mph",
      range: "423 mi",
      power: "286 HP",
      drivetrain: "High Torque RWD",
    },
    additionalSpecs: [
      { label: "Battery Capacities", value: "59 kWh & 79 kWh", iconName: "battery" },
      { label: "Charging Speed", value: "20% to 80% in 20 mins", iconName: "zap" },
      { label: "Cabin Tech Layout", value: "Dual 12.3\" Screen Panel", iconName: "smartphone" },
      { label: "Audio System", value: "Harman Kardon Premium", iconName: "volume-2" },
      { label: "Safety Suite", value: "6 Airbags & Level 2 ADAS", iconName: "shield" },
    ],
    colors: [
      { name: "Cyber Silver Matte", hex: "#A8ADB1", price: 0 },
      { name: "Stealth Iron Black", hex: "#232628", price: 90000 },
      { name: "Electric Blue Burst", hex: "#0047AB", price: 90000 },
    ],
    trims: [
      { name: "SEV Stealth Tech", description: "High-contrast digital glass canopy, carbon-fiber composites, active predictive handling.", price: 0 },
      { name: "SEV Circuit Master", description: "Fully customized racing cockpit, dual digital HUD, track performance logging, active aerodynamic stabilizers.", price: 950000 },
    ],
    wheels: [
      { name: "19\" Aero Alloy Wheels", imageUrl: "", price: 0 },
      { name: "20\" Blade-Runner Concept Alloys", imageUrl: "", price: 250000 },
    ],
    isLaunched: true,
  },
  {
    id: "creta-ev",
    name: "Creta EV",
    brand: "Hyundai",
    category: "Electric Vehicles",
    price: 1799000,
    imageUrl: IMAGES.vf8,
    tagline: "Electric Agility for the Modern Era",
    description: "Hyundai Creta EV introduces quiet, refined electric performance to the legendary SUV platform. Crafted with aerodynamically optimized panels, it offers quick response steering and smart connected features built around premium metropolitan commutes.",
    specs: {
      acceleration: "8.2s",
      topSpeed: "99 mph",
      range: "317 mi",
      power: "171 HP",
      drivetrain: "Front Wheel Drive",
    },
    additionalSpecs: [
      { label: "Battery Capacities", value: "42 kWh & 51.4 kWh", iconName: "battery" },
      { label: "Charging Speed", value: "10% to 80% in 58 mins", iconName: "zap" },
      { label: "Display Setup", value: "Dual 10.25\" Screen Panel", iconName: "tv" },
      { label: "Active Safety", value: "ADAS Level 2 certified", iconName: "shield" },
      { label: "Wheels Config", value: "17\" Aero Alloy Wheels", iconName: "cog" },
    ],
    colors: [
      { name: "Eco Grey Matte", hex: "#7D8285", price: 0 },
      { name: "Crimson Red", hex: "#B81D24", price: 60000 },
      { name: "Creta Blue Pearl", hex: "#194F90", price: 60000 },
    ],
    trims: [
      { name: "Smart Edition", description: "Full digital infotainment wrap, premium seating fabrics, and active steering safety.", price: 0 },
      { name: "Excellence Premium", description: "Adds genuine leather ventilation, active ADAS Level 2 suite, panoramic skylight, and fast charging upgrade.", price: 480000 },
    ],
    wheels: [
      { name: "17\" Aero Alloy Wheels", imageUrl: "", price: 0 },
      { name: "18\" High-Contrast Platinum", imageUrl: "", price: 120000 },
    ],
    isLaunched: true,
  },
  {
    id: "safari-dark",
    name: "Safari Dark Edition",
    brand: "Tata",
    category: "Performance Lab",
    price: 2069000,
    imageUrl: IMAGES.safariDark,
    tagline: "An Elegant Shadow of Power",
    description: "Cloaked in absolute mystery. The Safari Dark Edition features a stunning Oberon Black exterior with a deep piano-black front grille, pristine dark-grey trim elements, and signature dark-stonewashed premium leather seating. This premium 3-row cruiser commands silence while offering unmatched acoustic isolation.",
    specs: {
      acceleration: "8.7s",
      topSpeed: "118 mph",
      range: "N/A",
      power: "170 HP",
      drivetrain: "FWD / Terrain Active",
    },
    additionalSpecs: [
      { label: "Engine", value: "2.0L Kryotec Turbo", iconName: "cog" },
      { label: "Seating Layout", value: "6 or 7-Seater Luxury", iconName: "users" },
      { label: "Acoustics", value: "JBL 10-speaker Spatial", iconName: "music" },
      { label: "Air Purification", value: "Ozone Auto Shield", iconName: "shield" },
    ],
    colors: [
      { name: "Oberon Black", hex: "#121314", price: 0 },
      { name: "Cosmic Charcoal Matte", hex: "#2E3033", price: 100000 },
    ],
    trims: [
      { name: "Dark Adventure", description: "Black-themed body lining, dark alloys, fully digital dashboard, ventilating pilot captain seats.", price: 0 },
      { name: "Dark Accomplished Plus", description: "Adds dynamic gesture tailgate, memory seats, personalized welcoming visual signatures, dynamic ADAS Suite.", price: 300000 },
    ],
    wheels: [
      { name: "19\" Blackstone Alloy", imageUrl: "", price: 0 },
      { name: "20\" Dark Stealth Multi-Spoke", imageUrl: "", price: 150000 },
    ],
    isLaunched: true,
  },
  {
    id: "xuv700",
    name: "XUV 7XO",
    brand: "Mahindra",
    category: "Luxury SUVs",
    price: 2549000,
    imageUrl: IMAGES.xuv700,
    tagline: "Uncompromised Safety. Intelligent Power.",
    description: "Engineered to deliver exceptional security and performance across all landscapes. The XUV 7XO stands out with a robust structural shell, dual 10.25-inch high-resolution cinematic display screens, ADAS safety features, and a high-efficiency performance powertrain that turns every mountain road into a tranquil breeze.",
    specs: {
      acceleration: "9.2s",
      topSpeed: "121 mph",
      range: "N/A",
      power: "200 HP",
      drivetrain: "Intelligent AWD",
    },
    additionalSpecs: [
      { label: "Engine", value: "2.0L mStallion Turbo", iconName: "cog" },
      { label: "Cabin Tech", value: "AdreNoX Connect System", iconName: "smartphone" },
      { label: "Sunroof", value: "Panoramic Skyroof", iconName: "sun" },
      { label: "ADAS Tech", value: "ADAS Level 2 certified", iconName: "shield" },
    ],
    colors: [
      { name: "Everest White Pearl", hex: "#F3F5F7", price: 0 },
      { name: "Midnight Black Blue", hex: "#0A131F", price: 0 },
      { name: "Dazzling Silver Metallic", hex: "#D6D9DC", price: 0 },
      { name: "Electric Blue", hex: "#11468F", price: 50000 },
    ],
    trims: [
      { name: "AX7 Premium", description: "Comprehensive driver-assist, premium seating comfort, full digital AdreNoX setup.", price: 0 },
      { name: "AX7 Luxury Pack", description: "Adds 3D Immersive Audio by Sony (12-spk), Blind-view monitor, 360 camera, electronic smart door handles.", price: 290000 },
    ],
    wheels: [
      { name: "18\" Diamond Cut Alloys", imageUrl: "", price: 0 },
      { name: "19\" Custom Chrome Spoke", imageUrl: "", price: 110000 },
    ],
    isLaunched: true,
  },
  {
    id: "safari-silver",
    name: "Safari Accomplished Plus",
    brand: "Tata",
    category: "Luxury SUVs",
    price: 2249000,
    imageUrl: IMAGES.safari,
    tagline: "An Icon of Modern Prestige",
    description: "Combining majestic presence with intricate digital craft. Designed with an assertive geometric stance, premium silver highlights, and a luxurious dual-tone dashboard, it elevates family cruiser travel. Pampering captain seating and personalized cabin settings provide immense decision-breathing-room on long commutes.",
    specs: {
      acceleration: "9.5s",
      topSpeed: "115 mph",
      range: "N/A",
      power: "170 HP",
      drivetrain: "FWD / Multi-Terrain",
    },
    additionalSpecs: [
      { label: "Engine", value: "2.0L Kryotec Diesel", iconName: "cog" },
      { label: "Acoustics", value: "JBL Premium 9-speaker", iconName: "music" },
      { label: "Headlights", value: "Sequential LED Bars", iconName: "eye" },
      { label: "Climate Control", value: "Dual Zone Auto Air", iconName: "wind" },
    ],
    colors: [
      { name: "Stellar Silver", hex: "#D0D3D4", price: 0 },
      { name: "Glacier White", hex: "#F7F9FA", price: 0 },
      { name: "Galactic Grey", hex: "#63666A", price: 45000 },
    ],
    trims: [
      { name: "Adventure Plus", description: "Electronic stability, 19\" alloys, wireless smartphone charging, voice sunroof.", price: 0 },
      { name: "Accomplished Plus", description: "Panoramic sky canopy with mood lighting, 360-degree surround vision camera, luxury ventilation for first 2 rows.", price: 340000 },
    ],
    wheels: [
      { name: "19\" Sleek Sport Alloys", imageUrl: "", price: 0 },
      { name: "20\" Satin Finish Chrome", imageUrl: "", price: 130000 },
    ],
    isLaunched: true,
  },
  {
    id: "xuv-3xo",
    name: "XUV 3XO AX7 L",
    brand: "Mahindra",
    category: "Performance Lab",
    price: 1399000,
    imageUrl: IMAGES.xuv3xo,
    tagline: "Athletic Spirit. Urban Command.",
    description: "Compact yet aggressive, the XUV 3XO packs a staggering amount of technical sophistication and high-performance engineering. Featuring a refined mStallion TGDi turbo engine, segment-first level 2 ADAS capabilities, and a sweeping skyroof, it navigates congested cities and coastal lanes with unparalleled agility.",
    specs: {
      acceleration: "8.9s",
      topSpeed: "112 mph",
      range: "N/A",
      power: "130 HP",
      drivetrain: "FWD / Sport Tuned",
    },
    additionalSpecs: [
      { label: "Engine", value: "1.2L mStallion Turbo", iconName: "cog" },
      { label: "Safety ADAS", value: "Level 2 (10+ features)", iconName: "shield" },
      { label: "Sound Integration", value: "Harman Kardon Premium", iconName: "volume-2" },
      { label: "Fast Steering", value: "Electronic Sport Calibrated", iconName: "target" },
    ],
    colors: [
      { name: "Earthy Bronze Metallic", hex: "#8A6D53", price: 0 },
      { name: "Nebula Blue Accent", hex: "#1A365D", price: 40000 },
      { name: "Stealth Black", hex: "#1C1C1C", price: 40000 },
      { name: "Ivory White Premium", hex: "#FDFDFD", price: 0 },
    ],
    trims: [
      { name: "AX7 Comfort Tech", description: "Premium fabric dashboard wrap, dual screen 10.25\" infotainment, panoramic sunroof.", price: 0 },
      { name: "AX7 Luxury Edition", description: "Adds Electronic Parking Brake, 360-degree vision, premium Harman Kardon acoustics, blind spot monitor.", price: 180000 },
    ],
    wheels: [
      { name: "17\" Diamond-Cut Alloys", imageUrl: "", price: 0 },
      { name: "18\" Midnight-Black Alloys", imageUrl: "", price: 80000 },
    ],
    isLaunched: true,
  }
];

export const TEST_LOCATIONS = [
  "AutoHaven Beverly Hills Gallery",
  "AutoHaven Silicon Valley Tech Lab",
  "AutoHaven Miami Beach Lounge",
  "AutoHaven Seattle Waterfront Studio"
];
